/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuthenticationResponseDTO
 */
export interface AuthenticationResponseDTO {

    /**
     * @type {string}
     * @memberof AuthenticationResponseDTO
     */
    username?: string;

    /**
     * @type {string}
     * @memberof AuthenticationResponseDTO
     */
    role?: AuthenticationResponseDTORoleEnum;

    /**
     * @type {string}
     * @memberof AuthenticationResponseDTO
     */
    accessToken?: string;

    /**
     * @type {string}
     * @memberof AuthenticationResponseDTO
     */
    refreshToken?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum AuthenticationResponseDTORoleEnum {
    USER = 'USER',
    ADMIN = 'ADMIN'
}

