/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BookDTO
 */
export interface BookDTO {

    /**
     * @type {number}
     * @memberof BookDTO
     */
    id?: number;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    title?: string;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    author?: string;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    publisher?: string;

    /**
     * @type {Array<string>}
     * @memberof BookDTO
     */
    genres?: Array<BookDTOGenresEnum>;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    description?: string;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    coverUrl?: string;

    /**
     * @type {boolean}
     * @memberof BookDTO
     */
    isFeatured?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum BookDTOGenresEnum {
    FICTION = 'FICTION',
    NONFICTION = 'NON_FICTION',
    MYSTERY = 'MYSTERY',
    THRILLER = 'THRILLER',
    HORROR = 'HORROR',
    ROMANCE = 'ROMANCE',
    FANTASY = 'FANTASY',
    SCIENCEFICTION = 'SCIENCE_FICTION',
    DYSTOPIAN = 'DYSTOPIAN',
    HISTORICALFICTION = 'HISTORICAL_FICTION',
    BIOGRAPHY = 'BIOGRAPHY',
    AUTOBIOGRAPHY = 'AUTOBIOGRAPHY',
    MEMOIR = 'MEMOIR',
    SELFHELP = 'SELF_HELP',
    HEALTH = 'HEALTH',
    TRAVEL = 'TRAVEL',
    GUIDE = 'GUIDE',
    RELIGION = 'RELIGION',
    SCIENCE = 'SCIENCE',
    HISTORY = 'HISTORY',
    POETRY = 'POETRY',
    ART = 'ART',
    COOKBOOK = 'COOKBOOK',
    CHILDREN = 'CHILDREN',
    YOUNGADULT = 'YOUNG_ADULT',
    CLASSIC = 'CLASSIC',
    COMIC = 'COMIC',
    GRAPHICNOVEL = 'GRAPHIC_NOVEL',
    ANTHOLOGY = 'ANTHOLOGY',
    CRIME = 'CRIME',
    PHILOSOPHY = 'PHILOSOPHY',
    EDUCATIONAL = 'EDUCATIONAL'
}

export const BookGenreLabels: Record<BookDTOGenresEnum, string> = {
    [BookDTOGenresEnum.FICTION]: 'Fiction',
    [BookDTOGenresEnum.NONFICTION]: 'Non-fiction',
    [BookDTOGenresEnum.MYSTERY]: 'Mystery',
    [BookDTOGenresEnum.THRILLER]: 'Thriller',
    [BookDTOGenresEnum.HORROR]: 'Horror',
    [BookDTOGenresEnum.ROMANCE]: 'Romance',
    [BookDTOGenresEnum.FANTASY]: 'Fantasy',
    [BookDTOGenresEnum.SCIENCEFICTION]: 'Science Fiction',
    [BookDTOGenresEnum.DYSTOPIAN]: 'Dystopian',
    [BookDTOGenresEnum.HISTORICALFICTION]: 'Historical Fiction',
    [BookDTOGenresEnum.BIOGRAPHY]: 'Biography',
    [BookDTOGenresEnum.AUTOBIOGRAPHY]: 'Autobiography',
    [BookDTOGenresEnum.MEMOIR]: 'Memoir',
    [BookDTOGenresEnum.SELFHELP]: 'Self-help',
    [BookDTOGenresEnum.HEALTH]: 'Health',
    [BookDTOGenresEnum.TRAVEL]: 'Travel',
    [BookDTOGenresEnum.GUIDE]: 'Guide',
    [BookDTOGenresEnum.RELIGION]: 'Religion',
    [BookDTOGenresEnum.SCIENCE]: 'Science',
    [BookDTOGenresEnum.HISTORY]: 'History',
    [BookDTOGenresEnum.POETRY]: 'Poetry',
    [BookDTOGenresEnum.ART]: 'Art',
    [BookDTOGenresEnum.COOKBOOK]: 'Cookbook',
    [BookDTOGenresEnum.CHILDREN]: "Children's", 
    [BookDTOGenresEnum.YOUNGADULT]: 'Young Adult',
    [BookDTOGenresEnum.CLASSIC]: 'Classic',
    [BookDTOGenresEnum.COMIC]: 'Comic',
    [BookDTOGenresEnum.GRAPHICNOVEL]: 'Graphic Novel',
    [BookDTOGenresEnum.ANTHOLOGY]: 'Anthology',
    [BookDTOGenresEnum.CRIME]: 'Crime',
    [BookDTOGenresEnum.PHILOSOPHY]: 'Philosophy',
    [BookDTOGenresEnum.EDUCATIONAL]: 'Educational',
};

export function getBookGenreLabel(genre: BookDTOGenresEnum): string {
    return BookGenreLabels[genre] || genre;
}

