/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BookDTO
 */
export interface BookDTO {

    /**
     * @type {number}
     * @memberof BookDTO
     */
    id?: number;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    title?: string;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    author?: string;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    publisher?: string;

    /**
     * @type {Array<string>}
     * @memberof BookDTO
     */
    genres?: Array<BookDTOGenresEnum>;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    description?: string;

    /**
     * @type {string}
     * @memberof BookDTO
     */
    coverUrl?: string;

    /**
     * @type {boolean}
     * @memberof BookDTO
     */
    isFeatured?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum BookDTOGenresEnum {
    FICTION = 'FICTION',
    NONFICTION = 'NON_FICTION',
    MYSTERY = 'MYSTERY',
    THRILLER = 'THRILLER',
    HORROR = 'HORROR',
    ROMANCE = 'ROMANCE',
    FANTASY = 'FANTASY',
    SCIENCEFICTION = 'SCIENCE_FICTION',
    DYSTOPIAN = 'DYSTOPIAN',
    HISTORICALFICTION = 'HISTORICAL_FICTION',
    BIOGRAPHY = 'BIOGRAPHY',
    AUTOBIOGRAPHY = 'AUTOBIOGRAPHY',
    MEMOIR = 'MEMOIR',
    SELFHELP = 'SELF_HELP',
    HEALTH = 'HEALTH',
    TRAVEL = 'TRAVEL',
    GUIDE = 'GUIDE',
    RELIGION = 'RELIGION',
    SCIENCE = 'SCIENCE',
    HISTORY = 'HISTORY',
    POETRY = 'POETRY',
    ART = 'ART',
    COOKBOOK = 'COOKBOOK',
    CHILDREN = 'CHILDREN',
    YOUNGADULT = 'YOUNG_ADULT',
    CLASSIC = 'CLASSIC',
    COMIC = 'COMIC',
    GRAPHICNOVEL = 'GRAPHIC_NOVEL',
    ANTHOLOGY = 'ANTHOLOGY',
    CRIME = 'CRIME',
    PHILOSOPHY = 'PHILOSOPHY',
    EDUCATIONAL = 'EDUCATIONAL'
}

