/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BookDTO } from './book-dto';
 /**
 * 
 *
 * @export
 * @interface PageWrapperBookDTO
 */
export interface PageWrapperBookDTO {

    /**
     * @type {number}
     * @memberof PageWrapperBookDTO
     */
    totalPages?: number;

    /**
     * @type {number}
     * @memberof PageWrapperBookDTO
     */
    totalElements?: number;

    /**
     * @type {boolean}
     * @memberof PageWrapperBookDTO
     */
    hasNext?: boolean;

    /**
     * @type {boolean}
     * @memberof PageWrapperBookDTO
     */
    hasPrevious?: boolean;

    /**
     * @type {Array<BookDTO>}
     * @memberof PageWrapperBookDTO
     */
    content?: Array<BookDTO>;
}
