/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserDTO } from './user-dto';
 /**
 * 
 *
 * @export
 * @interface PageWrapperUserDTO
 */
export interface PageWrapperUserDTO {

    /**
     * @type {number}
     * @memberof PageWrapperUserDTO
     */
    totalPages?: number;

    /**
     * @type {number}
     * @memberof PageWrapperUserDTO
     */
    totalElements?: number;

    /**
     * @type {boolean}
     * @memberof PageWrapperUserDTO
     */
    hasNext?: boolean;

    /**
     * @type {boolean}
     * @memberof PageWrapperUserDTO
     */
    hasPrevious?: boolean;

    /**
     * @type {Array<UserDTO>}
     * @memberof PageWrapperUserDTO
     */
    content?: Array<UserDTO>;
}
