/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ReviewDTO } from './review-dto';
 /**
 * 
 *
 * @export
 * @interface PageWrapperReviewDTO
 */
export interface PageWrapperReviewDTO {

    /**
     * @type {number}
     * @memberof PageWrapperReviewDTO
     */
    totalPages?: number;

    /**
     * @type {number}
     * @memberof PageWrapperReviewDTO
     */
    totalElements?: number;

    /**
     * @type {boolean}
     * @memberof PageWrapperReviewDTO
     */
    hasNext?: boolean;

    /**
     * @type {boolean}
     * @memberof PageWrapperReviewDTO
     */
    hasPrevious?: boolean;

    /**
     * @type {Array<ReviewDTO>}
     * @memberof PageWrapperReviewDTO
     */
    content?: Array<ReviewDTO>;
}
