/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { type BookBarebonesDTO } from './book-barebones-dto';
 /**
 * 
 *
 * @export
 * @interface ReadingListDTO
 */
export interface ReadingListDTO {

    /**
     * @type {number}
     * @memberof ReadingListDTO
     */
    id?: number;

    /**
     * @type {string}
     * @memberof ReadingListDTO
     */
    username?: string;

    /**
     * @type {BookBarebonesDTO}
     * @memberof ReadingListDTO
     */
    book?: BookBarebonesDTO;

    /**
     * @type {Date}
     * @memberof ReadingListDTO
     */
    addedAt?: Date;

    /**
     * @type {Date}
     * @memberof ReadingListDTO
     */
    startedAt?: Date;

    /**
     * @type {Date}
     * @memberof ReadingListDTO
     */
    completedAt?: Date;

    /**
     * @type {string}
     * @memberof ReadingListDTO
     */
    status?: ReadingListDTOStatusEnum;

    /**
     * @type {number}
     * @memberof ReadingListDTO
     */
    rating?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ReadingListDTOStatusEnum {
    PLANTOREAD = 'PLAN_TO_READ',
    READING = 'READING',
    COMPLETED = 'COMPLETED',
    ONHOLD = 'ON_HOLD',
    DROPPED = 'DROPPED'
}

export const ReadingListStatusLabels: Record<ReadingListDTOStatusEnum, string> = {
    [ReadingListDTOStatusEnum.PLANTOREAD]: 'Plan to Read',
    [ReadingListDTOStatusEnum.READING]: 'Reading',
    [ReadingListDTOStatusEnum.COMPLETED]: 'Completed',
    [ReadingListDTOStatusEnum.ONHOLD]: 'On Hold',
    [ReadingListDTOStatusEnum.DROPPED]: 'Dropped'
};

export function getReadingListStatusLabel(status: ReadingListDTOStatusEnum): string {
    return ReadingListStatusLabels[status] || status;
}

