/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 import type {ReadingListDTOStatusEnum} from "@/types/reading-list-dto.ts";

/**
 * 
 *
 * @export
 * @interface ReadingListRequestDTO
 */
export interface ReadingListRequestDTO {

    /**
     * @type {number}
     * @memberof ReadingListRequestDTO
     */
    bookID: number;

    /**
     * @type {string}
     * @memberof ReadingListRequestDTO
     */
    status?: ReadingListDTOStatusEnum;

    /**
     * @type {number}
     * @memberof ReadingListRequestDTO
     */
    rating?: number;
}

/**
 * @export
 * @enum {string}
 */


