package io.hahn.bookspaceback.entity.enums;

public enum Genre {
    FICTION,
    NON_FICTION,
    MYSTERY,
    THRILLER,
    HORROR,
    ROMANCE,
    FANTASY,
    SCIENCE_FICTION,
    DYSTOPIAN,
    HISTORICAL_FICTION,
    BIOGRAPHY,
    AUTOBIOGRAPHY,
    MEMOIR,
    SELF_HELP,
    HEALTH,
    TRAVEL,
    GUIDE,
    RELIGION,
    SCIENCE,
    HISTORY,
    POETRY,
    ART,
    COOKBOOK,
    CHILDREN,
    YOUNG_ADULT,
    CLASSIC,
    COMIC,
    GRAPHIC_NOVEL,
    ANTHOLOGY,
    CRIME,
    PHILOSOPHY,
    EDUCATIONAL
}
