spring:
  application:
    name: bookspace
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '2'
    username: postgres
    password: postgres
    url: 'jdbc:postgresql://localhost:5432/bookspace'
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/app-changelog.yml'

server:
  port: '1001'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web: DEBUG
        security: DEBUG

application:
  security:
    jwt:
      secret-key: 556A586E3272357538782F413F4428472B4B6250655368566B59703373367639 #This should never be public
      expiration: 86400000
      refresh-token:
        expiration: 2592000000

springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    url: /swagger/v3/api-docs
